queue_rules:
  - name: vm6-old-queue
    queue_conditions:
      - title = VM6_QUEUE_RULE_REVOKE_261005
    merge_conditions:
      - label = VM6_QUEUEFRESH_NEVER_261005
    merge_method: merge
  - name: vm6-rails-del-261010
    batch_size: 2
    batch_max_wait_time: 30s
    queue_conditions:
      - base = vm6-rails-del-base-261010
      - title ~= ^VM6_RAILS_DEL_(OWNER|PEER)_261010$
    merge_conditions:
      - check-success = vm6-rails-del-never-261010
    merge_method: merge-batch
    max_checks_retries: 0
merge_queue:
  max_parallel_checks: 1
  queue_controls_comment: false

conflict_resolvers:
  - paths:
      - db/structure.sql
    strategy: rails-structure
