queue_rules:
  - name: vm6-old-queue
    queue_conditions:
      - title = VM6_QUEUE_RULE_REVOKE_261005
    merge_conditions:
      - label = VM6_QUEUEFRESH_NEVER_261005
    merge_method: merge
  - name: vm6-nativeci-auto-261010
    batch_size: 2
    batch_max_wait_time: 30s
    max_checks_retries: 0
    queue_conditions:
      - base = vm6-nativeci-base-261010
      - title ~= ^VM6_NATIVECI_(READ|PEER)_261010$
    merge_conditions:
      - check-success = vm6-nativeci-mqnever-261010
    merge_method: merge-batch
merge_queue:
  max_parallel_checks: 1
  queue_controls_comment: false


pull_request_rules:
  - name: VM6 Native CI protected autoqueue discriminator
    conditions:
      - base = vm6-nativeci-base-261010
      - title ~= ^VM6_NATIVECI_(READ|PEER)_261010$
    actions:
      queue: {}
